name: dart_side
description: A Simple and Pure Dart Http Server for Small Projects

version: 0.0.1-dev

homepage: https://github.com/DizoftTeam/dart_side

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  lint: ^1.3.0
  test: ^1.14.4
